create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name varchar(20) not null,
  name_key varchar(20) not null unique,
  elo integer not null default 1200 check (elo between 100 and 4000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists players_elo_ranking_idx
  on public.players (elo desc, updated_at asc);

alter table public.players enable row level security;


-- Autorise uniquement le backend Netlify utilisant la Secret key.
-- Le rôle service_role contourne le RLS, mais il doit quand même
-- disposer des privilèges SQL sur les objets exposés par la Data API.
grant usage on schema public to service_role;
grant select, insert, update, delete on table public.players to service_role;
grant usage, select on sequence public.players_id_seq to service_role;
