create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name varchar(20) not null,
  name_key varchar(20) not null unique,
  elo integer not null default 1200 check (elo between 100 and 4000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists players_elo_ranking_idx
  on public.players (elo desc, updated_at asc);

alter table public.players enable row level security;
