create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name varchar(20) not null,
  name_key varchar(20) not null unique,
  elo integer not null default 1200 check (elo between 100 and 4000),
  password_hash text,
  password_salt text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Pour les projets déjà créés avec v51/v52 :
alter table public.players
  add column if not exists password_hash text;

alter table public.players
  add column if not exists password_salt text;

create unique index if not exists players_name_key_unique
  on public.players (name_key);

create index if not exists players_elo_ranking_idx
  on public.players (elo desc, updated_at asc);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists sessions_token_hash_idx
  on public.sessions (token_hash);

create index if not exists sessions_player_idx
  on public.sessions (player_id);

alter table public.players enable row level security;
alter table public.sessions enable row level security;

-- Le navigateur n'accède jamais directement à ces tables.
-- Seules les Netlify Functions utilisent la Secret key / service_role.
grant usage on schema public to service_role;

grant select, insert, update, delete
  on table public.players
  to service_role;

grant select, insert, update, delete
  on table public.sessions
  to service_role;

grant usage, select
  on sequence public.players_id_seq
  to service_role;

grant usage, select
  on sequence public.sessions_id_seq
  to service_role;
