CREATE TABLE IF NOT EXISTS players (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(20) NOT NULL,
  elo INTEGER NOT NULL DEFAULT 1200 CHECK (elo BETWEEN 100 AND 4000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS players_name_ci_unique
  ON players ((LOWER(name)));

CREATE INDEX IF NOT EXISTS players_elo_ranking_idx
  ON players (elo DESC, updated_at ASC);
